# Generated by Django 5.2.6 on 2025-09-10 21:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='area',
            options={'verbose_name': 'Area', 'verbose_name_plural': 'Aree'},
        ),
        migrations.AlterModelOptions(
            name='cleaningmachine',
            options={'verbose_name': 'Macchina Spazzatrice', 'verbose_name_plural': 'Macchine Spazzatrici'},
        ),
        migrations.AlterModelOptions(
            name='passageplan',
            options={'verbose_name': 'Piano Passaggi', 'verbose_name_plural': 'Piani Passaggi'},
        ),
        migrations.AlterModelOptions(
            name='street',
            options={'verbose_name': 'Strada', 'verbose_name_plural': 'Strade'},
        ),
        migrations.AlterModelOptions(
            name='workorder',
            options={'verbose_name': 'Ordine di Lavoro', 'verbose_name_plural': 'Ordini di Lavoro'},
        ),
        migrations.AlterField(
            model_name='area',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Creata il'),
        ),
        migrations.AlterField(
            model_name='area',
            name='description',
            field=models.TextField(blank=True, verbose_name='Descrizione'),
        ),
        migrations.AlterField(
            model_name='area',
            name='name',
            field=models.CharField(max_length=100, unique=True, verbose_name='Nome'),
        ),
        migrations.AlterField(
            model_name='cleaningmachine',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Creato il'),
        ),
        migrations.AlterField(
            model_name='cleaningmachine',
            name='description',
            field=models.TextField(blank=True, verbose_name='Descrizione'),
        ),
        migrations.AlterField(
            model_name='cleaningmachine',
            name='name',
            field=models.CharField(max_length=100, unique=True, verbose_name='Nome'),
        ),
        migrations.AlterField(
            model_name='passageplan',
            name='cleaning_machine',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.cleaningmachine', verbose_name='Macchina Spazzatrice'),
        ),
        migrations.AlterField(
            model_name='passageplan',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Creato il'),
        ),
        migrations.AlterField(
            model_name='passageplan',
            name='day_of_month',
            field=models.PositiveIntegerField(verbose_name='Giorno del Mese'),
        ),
        migrations.AlterField(
            model_name='passageplan',
            name='month',
            field=models.PositiveIntegerField(verbose_name='Mese'),
        ),
        migrations.AlterField(
            model_name='passageplan',
            name='required_passages',
            field=models.PositiveIntegerField(verbose_name='Passaggi Richiesti'),
        ),
        migrations.AlterField(
            model_name='passageplan',
            name='year',
            field=models.PositiveIntegerField(verbose_name='Anno'),
        ),
        migrations.AlterField(
            model_name='street',
            name='area',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='streets', to='main.area', verbose_name='Area'),
        ),
        migrations.AlterField(
            model_name='street',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Creata il'),
        ),
        migrations.AlterField(
            model_name='street',
            name='name',
            field=models.CharField(max_length=200, verbose_name='Nome'),
        ),
        migrations.AlterField(
            model_name='workorder',
            name='cleaning_machine',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.cleaningmachine', verbose_name='Macchina Spazzatrice'),
        ),
        migrations.AlterField(
            model_name='workorder',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Creato il'),
        ),
        migrations.AlterField(
            model_name='workorder',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Creato da'),
        ),
        migrations.AlterField(
            model_name='workorder',
            name='daily_passages',
            field=models.PositiveIntegerField(verbose_name='Passaggi Giornalieri'),
        ),
        migrations.AlterField(
            model_name='workorder',
            name='date',
            field=models.DateField(verbose_name='Data'),
        ),
        migrations.AlterField(
            model_name='workorder',
            name='street',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.street', verbose_name='Strada'),
        ),
        migrations.AlterField(
            model_name='workorder',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Aggiornato il'),
        ),
    ]
