# Generated by Django 5.2.5 on 2025-09-11 06:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_area_options_alter_cleaningmachine_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CleaningOperationType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Nome')),
                ('description', models.TextField(blank=True, verbose_name='Descrizione')),
                ('frequency_per_week', models.PositiveIntegerField(default=1, verbose_name='Frequenza Settimanale')),
            ],
            options={
                'verbose_name': 'Tipo Operazione Pulizia',
                'verbose_name_plural': 'Tipi Operazioni Pulizia',
            },
        ),
        migrations.CreateModel(
            name='StreetCleaningOperation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_of_month', models.PositiveIntegerField(verbose_name='Giorno del Mese')),
                ('month', models.PositiveIntegerField(verbose_name='Mese')),
                ('year', models.PositiveIntegerField(verbose_name='Anno')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creata il')),
                ('operation_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.cleaningoperationtype', verbose_name='Tipo Operazione')),
                ('street', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='operations', to='main.street', verbose_name='Strada')),
            ],
            options={
                'verbose_name': 'Operazione Pulizia Strada',
                'verbose_name_plural': 'Operazioni Pulizia Strade',
                'constraints': [models.CheckConstraint(condition=models.Q(('day_of_month__gte', 1), ('day_of_month__lte', 31)), name='valid_operation_day'), models.CheckConstraint(condition=models.Q(('month__gte', 1), ('month__lte', 12)), name='valid_operation_month')],
                'unique_together': {('street', 'operation_type', 'day_of_month', 'month', 'year')},
            },
        ),
    ]
