# Generated by Django 5.2.5 on 2025-09-11 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_cleaningoperationtype_streetcleaningoperation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='streetcleaningoperation',
            name='day_of_month',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Giorno del Mese'),
        ),
    ]
