# Generated by Django 5.2.5 on 2025-09-11 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_streetcleaningoperation_day_of_month'),
    ]

    operations = [
        migrations.AlterField(
            model_name='streetcleaningoperation',
            name='month',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Mese'),
        ),
        migrations.AlterField(
            model_name='streetcleaningoperation',
            name='year',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Anno'),
        ),
    ]
